name: dart_snake
description: An absolute bare-bones web app.
# version: 1.0.0
#homepage: https://www.example.com
#author: Joost Heitbrink <email@example.com>

environment:
  sdk: ">=3.1.0"

#dependencies:
#  path: ^1.4.1

dev_dependencies:
  build_runner: ^2.4.6
  build_web_compilers: ^4.0.4
